FROM openjdk:8

ADD docker/preview_server/examples-preview-service-0.0.1-SNAPSHOT.jar examples-preview-service-0.0.1-SNAPSHOT.jar

ENTRYPOINT ["java", "-jar", "examples-preview-service-0.0.1-SNAPSHOT.jar"]
