// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/runtime/v1/lifecycle.proto

package spec.proto.runtime.v1;

public final class LifecycleProto {
  private LifecycleProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DynamicConfigurationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:spec.proto.runtime.v1.DynamicConfiguration)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Required. The dynamic configuration of a component
     * </pre>
     *
     * <code>.spec.proto.runtime.v1.ComponentConfig component_config = 1;</code>
     * @return Whether the componentConfig field is set.
     */
    boolean hasComponentConfig();
    /**
     * <pre>
     * Required. The dynamic configuration of a component
     * </pre>
     *
     * <code>.spec.proto.runtime.v1.ComponentConfig component_config = 1;</code>
     * @return The componentConfig.
     */
    spec.proto.runtime.v1.LifecycleProto.ComponentConfig getComponentConfig();
    /**
     * <pre>
     * Required. The dynamic configuration of a component
     * </pre>
     *
     * <code>.spec.proto.runtime.v1.ComponentConfig component_config = 1;</code>
     */
    spec.proto.runtime.v1.LifecycleProto.ComponentConfigOrBuilder getComponentConfigOrBuilder();
  }
  /**
   * <pre>
   * The dynamic configuration of the sidecar
   * </pre>
   *
   * Protobuf type {@code spec.proto.runtime.v1.DynamicConfiguration}
   */
  public  static final class DynamicConfiguration extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:spec.proto.runtime.v1.DynamicConfiguration)
      DynamicConfigurationOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DynamicConfiguration.newBuilder() to construct.
    private DynamicConfiguration(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DynamicConfiguration() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DynamicConfiguration();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DynamicConfiguration(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              spec.proto.runtime.v1.LifecycleProto.ComponentConfig.Builder subBuilder = null;
              if (componentConfig_ != null) {
                subBuilder = componentConfig_.toBuilder();
              }
              componentConfig_ = input.readMessage(spec.proto.runtime.v1.LifecycleProto.ComponentConfig.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(componentConfig_);
                componentConfig_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return spec.proto.runtime.v1.LifecycleProto.internal_static_spec_proto_runtime_v1_DynamicConfiguration_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return spec.proto.runtime.v1.LifecycleProto.internal_static_spec_proto_runtime_v1_DynamicConfiguration_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              spec.proto.runtime.v1.LifecycleProto.DynamicConfiguration.class, spec.proto.runtime.v1.LifecycleProto.DynamicConfiguration.Builder.class);
    }

    public static final int COMPONENT_CONFIG_FIELD_NUMBER = 1;
    private spec.proto.runtime.v1.LifecycleProto.ComponentConfig componentConfig_;
    /**
     * <pre>
     * Required. The dynamic configuration of a component
     * </pre>
     *
     * <code>.spec.proto.runtime.v1.ComponentConfig component_config = 1;</code>
     * @return Whether the componentConfig field is set.
     */
    public boolean hasComponentConfig() {
      return componentConfig_ != null;
    }
    /**
     * <pre>
     * Required. The dynamic configuration of a component
     * </pre>
     *
     * <code>.spec.proto.runtime.v1.ComponentConfig component_config = 1;</code>
     * @return The componentConfig.
     */
    public spec.proto.runtime.v1.LifecycleProto.ComponentConfig getComponentConfig() {
      return componentConfig_ == null ? spec.proto.runtime.v1.LifecycleProto.ComponentConfig.getDefaultInstance() : componentConfig_;
    }
    /**
     * <pre>
     * Required. The dynamic configuration of a component
     * </pre>
     *
     * <code>.spec.proto.runtime.v1.ComponentConfig component_config = 1;</code>
     */
    public spec.proto.runtime.v1.LifecycleProto.ComponentConfigOrBuilder getComponentConfigOrBuilder() {
      return getComponentConfig();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (componentConfig_ != null) {
        output.writeMessage(1, getComponentConfig());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (componentConfig_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getComponentConfig());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof spec.proto.runtime.v1.LifecycleProto.DynamicConfiguration)) {
        return super.equals(obj);
      }
      spec.proto.runtime.v1.LifecycleProto.DynamicConfiguration other = (spec.proto.runtime.v1.LifecycleProto.DynamicConfiguration) obj;

      if (hasComponentConfig() != other.hasComponentConfig()) return false;
      if (hasComponentConfig()) {
        if (!getComponentConfig()
            .equals(other.getComponentConfig())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasComponentConfig()) {
        hash = (37 * hash) + COMPONENT_CONFIG_FIELD_NUMBER;
        hash = (53 * hash) + getComponentConfig().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static spec.proto.runtime.v1.LifecycleProto.DynamicConfiguration parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static spec.proto.runtime.v1.LifecycleProto.DynamicConfiguration parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static spec.proto.runtime.v1.LifecycleProto.DynamicConfiguration parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static spec.proto.runtime.v1.LifecycleProto.DynamicConfiguration parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static spec.proto.runtime.v1.LifecycleProto.DynamicConfiguration parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static spec.proto.runtime.v1.LifecycleProto.DynamicConfiguration parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static spec.proto.runtime.v1.LifecycleProto.DynamicConfiguration parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static spec.proto.runtime.v1.LifecycleProto.DynamicConfiguration parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static spec.proto.runtime.v1.LifecycleProto.DynamicConfiguration parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static spec.proto.runtime.v1.LifecycleProto.DynamicConfiguration parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static spec.proto.runtime.v1.LifecycleProto.DynamicConfiguration parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static spec.proto.runtime.v1.LifecycleProto.DynamicConfiguration parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(spec.proto.runtime.v1.LifecycleProto.DynamicConfiguration prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * The dynamic configuration of the sidecar
     * </pre>
     *
     * Protobuf type {@code spec.proto.runtime.v1.DynamicConfiguration}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:spec.proto.runtime.v1.DynamicConfiguration)
        spec.proto.runtime.v1.LifecycleProto.DynamicConfigurationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return spec.proto.runtime.v1.LifecycleProto.internal_static_spec_proto_runtime_v1_DynamicConfiguration_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return spec.proto.runtime.v1.LifecycleProto.internal_static_spec_proto_runtime_v1_DynamicConfiguration_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                spec.proto.runtime.v1.LifecycleProto.DynamicConfiguration.class, spec.proto.runtime.v1.LifecycleProto.DynamicConfiguration.Builder.class);
      }

      // Construct using spec.proto.runtime.v1.LifecycleProto.DynamicConfiguration.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (componentConfigBuilder_ == null) {
          componentConfig_ = null;
        } else {
          componentConfig_ = null;
          componentConfigBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return spec.proto.runtime.v1.LifecycleProto.internal_static_spec_proto_runtime_v1_DynamicConfiguration_descriptor;
      }

      @java.lang.Override
      public spec.proto.runtime.v1.LifecycleProto.DynamicConfiguration getDefaultInstanceForType() {
        return spec.proto.runtime.v1.LifecycleProto.DynamicConfiguration.getDefaultInstance();
      }

      @java.lang.Override
      public spec.proto.runtime.v1.LifecycleProto.DynamicConfiguration build() {
        spec.proto.runtime.v1.LifecycleProto.DynamicConfiguration result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public spec.proto.runtime.v1.LifecycleProto.DynamicConfiguration buildPartial() {
        spec.proto.runtime.v1.LifecycleProto.DynamicConfiguration result = new spec.proto.runtime.v1.LifecycleProto.DynamicConfiguration(this);
        if (componentConfigBuilder_ == null) {
          result.componentConfig_ = componentConfig_;
        } else {
          result.componentConfig_ = componentConfigBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof spec.proto.runtime.v1.LifecycleProto.DynamicConfiguration) {
          return mergeFrom((spec.proto.runtime.v1.LifecycleProto.DynamicConfiguration)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(spec.proto.runtime.v1.LifecycleProto.DynamicConfiguration other) {
        if (other == spec.proto.runtime.v1.LifecycleProto.DynamicConfiguration.getDefaultInstance()) return this;
        if (other.hasComponentConfig()) {
          mergeComponentConfig(other.getComponentConfig());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        spec.proto.runtime.v1.LifecycleProto.DynamicConfiguration parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (spec.proto.runtime.v1.LifecycleProto.DynamicConfiguration) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private spec.proto.runtime.v1.LifecycleProto.ComponentConfig componentConfig_;
      private com.google.protobuf.SingleFieldBuilderV3<
          spec.proto.runtime.v1.LifecycleProto.ComponentConfig, spec.proto.runtime.v1.LifecycleProto.ComponentConfig.Builder, spec.proto.runtime.v1.LifecycleProto.ComponentConfigOrBuilder> componentConfigBuilder_;
      /**
       * <pre>
       * Required. The dynamic configuration of a component
       * </pre>
       *
       * <code>.spec.proto.runtime.v1.ComponentConfig component_config = 1;</code>
       * @return Whether the componentConfig field is set.
       */
      public boolean hasComponentConfig() {
        return componentConfigBuilder_ != null || componentConfig_ != null;
      }
      /**
       * <pre>
       * Required. The dynamic configuration of a component
       * </pre>
       *
       * <code>.spec.proto.runtime.v1.ComponentConfig component_config = 1;</code>
       * @return The componentConfig.
       */
      public spec.proto.runtime.v1.LifecycleProto.ComponentConfig getComponentConfig() {
        if (componentConfigBuilder_ == null) {
          return componentConfig_ == null ? spec.proto.runtime.v1.LifecycleProto.ComponentConfig.getDefaultInstance() : componentConfig_;
        } else {
          return componentConfigBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * Required. The dynamic configuration of a component
       * </pre>
       *
       * <code>.spec.proto.runtime.v1.ComponentConfig component_config = 1;</code>
       */
      public Builder setComponentConfig(spec.proto.runtime.v1.LifecycleProto.ComponentConfig value) {
        if (componentConfigBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          componentConfig_ = value;
          onChanged();
        } else {
          componentConfigBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * Required. The dynamic configuration of a component
       * </pre>
       *
       * <code>.spec.proto.runtime.v1.ComponentConfig component_config = 1;</code>
       */
      public Builder setComponentConfig(
          spec.proto.runtime.v1.LifecycleProto.ComponentConfig.Builder builderForValue) {
        if (componentConfigBuilder_ == null) {
          componentConfig_ = builderForValue.build();
          onChanged();
        } else {
          componentConfigBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * Required. The dynamic configuration of a component
       * </pre>
       *
       * <code>.spec.proto.runtime.v1.ComponentConfig component_config = 1;</code>
       */
      public Builder mergeComponentConfig(spec.proto.runtime.v1.LifecycleProto.ComponentConfig value) {
        if (componentConfigBuilder_ == null) {
          if (componentConfig_ != null) {
            componentConfig_ =
              spec.proto.runtime.v1.LifecycleProto.ComponentConfig.newBuilder(componentConfig_).mergeFrom(value).buildPartial();
          } else {
            componentConfig_ = value;
          }
          onChanged();
        } else {
          componentConfigBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * Required. The dynamic configuration of a component
       * </pre>
       *
       * <code>.spec.proto.runtime.v1.ComponentConfig component_config = 1;</code>
       */
      public Builder clearComponentConfig() {
        if (componentConfigBuilder_ == null) {
          componentConfig_ = null;
          onChanged();
        } else {
          componentConfig_ = null;
          componentConfigBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * Required. The dynamic configuration of a component
       * </pre>
       *
       * <code>.spec.proto.runtime.v1.ComponentConfig component_config = 1;</code>
       */
      public spec.proto.runtime.v1.LifecycleProto.ComponentConfig.Builder getComponentConfigBuilder() {
        
        onChanged();
        return getComponentConfigFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * Required. The dynamic configuration of a component
       * </pre>
       *
       * <code>.spec.proto.runtime.v1.ComponentConfig component_config = 1;</code>
       */
      public spec.proto.runtime.v1.LifecycleProto.ComponentConfigOrBuilder getComponentConfigOrBuilder() {
        if (componentConfigBuilder_ != null) {
          return componentConfigBuilder_.getMessageOrBuilder();
        } else {
          return componentConfig_ == null ?
              spec.proto.runtime.v1.LifecycleProto.ComponentConfig.getDefaultInstance() : componentConfig_;
        }
      }
      /**
       * <pre>
       * Required. The dynamic configuration of a component
       * </pre>
       *
       * <code>.spec.proto.runtime.v1.ComponentConfig component_config = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          spec.proto.runtime.v1.LifecycleProto.ComponentConfig, spec.proto.runtime.v1.LifecycleProto.ComponentConfig.Builder, spec.proto.runtime.v1.LifecycleProto.ComponentConfigOrBuilder> 
          getComponentConfigFieldBuilder() {
        if (componentConfigBuilder_ == null) {
          componentConfigBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              spec.proto.runtime.v1.LifecycleProto.ComponentConfig, spec.proto.runtime.v1.LifecycleProto.ComponentConfig.Builder, spec.proto.runtime.v1.LifecycleProto.ComponentConfigOrBuilder>(
                  getComponentConfig(),
                  getParentForChildren(),
                  isClean());
          componentConfig_ = null;
        }
        return componentConfigBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:spec.proto.runtime.v1.DynamicConfiguration)
    }

    // @@protoc_insertion_point(class_scope:spec.proto.runtime.v1.DynamicConfiguration)
    private static final spec.proto.runtime.v1.LifecycleProto.DynamicConfiguration DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new spec.proto.runtime.v1.LifecycleProto.DynamicConfiguration();
    }

    public static spec.proto.runtime.v1.LifecycleProto.DynamicConfiguration getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DynamicConfiguration>
        PARSER = new com.google.protobuf.AbstractParser<DynamicConfiguration>() {
      @java.lang.Override
      public DynamicConfiguration parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DynamicConfiguration(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DynamicConfiguration> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DynamicConfiguration> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public spec.proto.runtime.v1.LifecycleProto.DynamicConfiguration getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ApplyConfigurationResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:spec.proto.runtime.v1.ApplyConfigurationResponse)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * <pre>
   * The response of the `ApplyConfiguration` method.
   * </pre>
   *
   * Protobuf type {@code spec.proto.runtime.v1.ApplyConfigurationResponse}
   */
  public  static final class ApplyConfigurationResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:spec.proto.runtime.v1.ApplyConfigurationResponse)
      ApplyConfigurationResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ApplyConfigurationResponse.newBuilder() to construct.
    private ApplyConfigurationResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ApplyConfigurationResponse() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ApplyConfigurationResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ApplyConfigurationResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return spec.proto.runtime.v1.LifecycleProto.internal_static_spec_proto_runtime_v1_ApplyConfigurationResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return spec.proto.runtime.v1.LifecycleProto.internal_static_spec_proto_runtime_v1_ApplyConfigurationResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              spec.proto.runtime.v1.LifecycleProto.ApplyConfigurationResponse.class, spec.proto.runtime.v1.LifecycleProto.ApplyConfigurationResponse.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof spec.proto.runtime.v1.LifecycleProto.ApplyConfigurationResponse)) {
        return super.equals(obj);
      }
      spec.proto.runtime.v1.LifecycleProto.ApplyConfigurationResponse other = (spec.proto.runtime.v1.LifecycleProto.ApplyConfigurationResponse) obj;

      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static spec.proto.runtime.v1.LifecycleProto.ApplyConfigurationResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static spec.proto.runtime.v1.LifecycleProto.ApplyConfigurationResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static spec.proto.runtime.v1.LifecycleProto.ApplyConfigurationResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static spec.proto.runtime.v1.LifecycleProto.ApplyConfigurationResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static spec.proto.runtime.v1.LifecycleProto.ApplyConfigurationResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static spec.proto.runtime.v1.LifecycleProto.ApplyConfigurationResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static spec.proto.runtime.v1.LifecycleProto.ApplyConfigurationResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static spec.proto.runtime.v1.LifecycleProto.ApplyConfigurationResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static spec.proto.runtime.v1.LifecycleProto.ApplyConfigurationResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static spec.proto.runtime.v1.LifecycleProto.ApplyConfigurationResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static spec.proto.runtime.v1.LifecycleProto.ApplyConfigurationResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static spec.proto.runtime.v1.LifecycleProto.ApplyConfigurationResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(spec.proto.runtime.v1.LifecycleProto.ApplyConfigurationResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * The response of the `ApplyConfiguration` method.
     * </pre>
     *
     * Protobuf type {@code spec.proto.runtime.v1.ApplyConfigurationResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:spec.proto.runtime.v1.ApplyConfigurationResponse)
        spec.proto.runtime.v1.LifecycleProto.ApplyConfigurationResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return spec.proto.runtime.v1.LifecycleProto.internal_static_spec_proto_runtime_v1_ApplyConfigurationResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return spec.proto.runtime.v1.LifecycleProto.internal_static_spec_proto_runtime_v1_ApplyConfigurationResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                spec.proto.runtime.v1.LifecycleProto.ApplyConfigurationResponse.class, spec.proto.runtime.v1.LifecycleProto.ApplyConfigurationResponse.Builder.class);
      }

      // Construct using spec.proto.runtime.v1.LifecycleProto.ApplyConfigurationResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return spec.proto.runtime.v1.LifecycleProto.internal_static_spec_proto_runtime_v1_ApplyConfigurationResponse_descriptor;
      }

      @java.lang.Override
      public spec.proto.runtime.v1.LifecycleProto.ApplyConfigurationResponse getDefaultInstanceForType() {
        return spec.proto.runtime.v1.LifecycleProto.ApplyConfigurationResponse.getDefaultInstance();
      }

      @java.lang.Override
      public spec.proto.runtime.v1.LifecycleProto.ApplyConfigurationResponse build() {
        spec.proto.runtime.v1.LifecycleProto.ApplyConfigurationResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public spec.proto.runtime.v1.LifecycleProto.ApplyConfigurationResponse buildPartial() {
        spec.proto.runtime.v1.LifecycleProto.ApplyConfigurationResponse result = new spec.proto.runtime.v1.LifecycleProto.ApplyConfigurationResponse(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof spec.proto.runtime.v1.LifecycleProto.ApplyConfigurationResponse) {
          return mergeFrom((spec.proto.runtime.v1.LifecycleProto.ApplyConfigurationResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(spec.proto.runtime.v1.LifecycleProto.ApplyConfigurationResponse other) {
        if (other == spec.proto.runtime.v1.LifecycleProto.ApplyConfigurationResponse.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        spec.proto.runtime.v1.LifecycleProto.ApplyConfigurationResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (spec.proto.runtime.v1.LifecycleProto.ApplyConfigurationResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:spec.proto.runtime.v1.ApplyConfigurationResponse)
    }

    // @@protoc_insertion_point(class_scope:spec.proto.runtime.v1.ApplyConfigurationResponse)
    private static final spec.proto.runtime.v1.LifecycleProto.ApplyConfigurationResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new spec.proto.runtime.v1.LifecycleProto.ApplyConfigurationResponse();
    }

    public static spec.proto.runtime.v1.LifecycleProto.ApplyConfigurationResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ApplyConfigurationResponse>
        PARSER = new com.google.protobuf.AbstractParser<ApplyConfigurationResponse>() {
      @java.lang.Override
      public ApplyConfigurationResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ApplyConfigurationResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ApplyConfigurationResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ApplyConfigurationResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public spec.proto.runtime.v1.LifecycleProto.ApplyConfigurationResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ComponentConfigOrBuilder extends
      // @@protoc_insertion_point(interface_extends:spec.proto.runtime.v1.ComponentConfig)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Required. Which kind of API you are using, e.g. `lock`, `state`
     * </pre>
     *
     * <code>string kind = 1;</code>
     * @return The kind.
     */
    java.lang.String getKind();
    /**
     * <pre>
     * Required. Which kind of API you are using, e.g. `lock`, `state`
     * </pre>
     *
     * <code>string kind = 1;</code>
     * @return The bytes for kind.
     */
    com.google.protobuf.ByteString
        getKindBytes();

    /**
     * <pre>
     * Required. The component name, e.g. `state_demo`
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <pre>
     * Required. The component name, e.g. `state_demo`
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <pre>
     * Required. The dynamic configuration of this component
     * </pre>
     *
     * <code>map&lt;string, string&gt; metadata = 3;</code>
     */
    int getMetadataCount();
    /**
     * <pre>
     * Required. The dynamic configuration of this component
     * </pre>
     *
     * <code>map&lt;string, string&gt; metadata = 3;</code>
     */
    boolean containsMetadata(
        java.lang.String key);
    /**
     * Use {@link #getMetadataMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getMetadata();
    /**
     * <pre>
     * Required. The dynamic configuration of this component
     * </pre>
     *
     * <code>map&lt;string, string&gt; metadata = 3;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getMetadataMap();
    /**
     * <pre>
     * Required. The dynamic configuration of this component
     * </pre>
     *
     * <code>map&lt;string, string&gt; metadata = 3;</code>
     */

    java.lang.String getMetadataOrDefault(
        java.lang.String key,
        java.lang.String defaultValue);
    /**
     * <pre>
     * Required. The dynamic configuration of this component
     * </pre>
     *
     * <code>map&lt;string, string&gt; metadata = 3;</code>
     */

    java.lang.String getMetadataOrThrow(
        java.lang.String key);
  }
  /**
   * <pre>
   * The dynamic configuration of a component
   * </pre>
   *
   * Protobuf type {@code spec.proto.runtime.v1.ComponentConfig}
   */
  public  static final class ComponentConfig extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:spec.proto.runtime.v1.ComponentConfig)
      ComponentConfigOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ComponentConfig.newBuilder() to construct.
    private ComponentConfig(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ComponentConfig() {
      kind_ = "";
      name_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ComponentConfig();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ComponentConfig(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              kind_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                metadata_ = com.google.protobuf.MapField.newMapField(
                    MetadataDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              metadata__ = input.readMessage(
                  MetadataDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              metadata_.getMutableMap().put(
                  metadata__.getKey(), metadata__.getValue());
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return spec.proto.runtime.v1.LifecycleProto.internal_static_spec_proto_runtime_v1_ComponentConfig_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 3:
          return internalGetMetadata();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return spec.proto.runtime.v1.LifecycleProto.internal_static_spec_proto_runtime_v1_ComponentConfig_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              spec.proto.runtime.v1.LifecycleProto.ComponentConfig.class, spec.proto.runtime.v1.LifecycleProto.ComponentConfig.Builder.class);
    }

    public static final int KIND_FIELD_NUMBER = 1;
    private volatile java.lang.Object kind_;
    /**
     * <pre>
     * Required. Which kind of API you are using, e.g. `lock`, `state`
     * </pre>
     *
     * <code>string kind = 1;</code>
     * @return The kind.
     */
    public java.lang.String getKind() {
      java.lang.Object ref = kind_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        kind_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Required. Which kind of API you are using, e.g. `lock`, `state`
     * </pre>
     *
     * <code>string kind = 1;</code>
     * @return The bytes for kind.
     */
    public com.google.protobuf.ByteString
        getKindBytes() {
      java.lang.Object ref = kind_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        kind_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <pre>
     * Required. The component name, e.g. `state_demo`
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Required. The component name, e.g. `state_demo`
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int METADATA_FIELD_NUMBER = 3;
    private static final class MetadataDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  spec.proto.runtime.v1.LifecycleProto.internal_static_spec_proto_runtime_v1_ComponentConfig_MetadataEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> metadata_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetMetadata() {
      if (metadata_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            MetadataDefaultEntryHolder.defaultEntry);
      }
      return metadata_;
    }

    public int getMetadataCount() {
      return internalGetMetadata().getMap().size();
    }
    /**
     * <pre>
     * Required. The dynamic configuration of this component
     * </pre>
     *
     * <code>map&lt;string, string&gt; metadata = 3;</code>
     */

    public boolean containsMetadata(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetMetadata().getMap().containsKey(key);
    }
    /**
     * Use {@link #getMetadataMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getMetadata() {
      return getMetadataMap();
    }
    /**
     * <pre>
     * Required. The dynamic configuration of this component
     * </pre>
     *
     * <code>map&lt;string, string&gt; metadata = 3;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getMetadataMap() {
      return internalGetMetadata().getMap();
    }
    /**
     * <pre>
     * Required. The dynamic configuration of this component
     * </pre>
     *
     * <code>map&lt;string, string&gt; metadata = 3;</code>
     */

    public java.lang.String getMetadataOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetMetadata().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * Required. The dynamic configuration of this component
     * </pre>
     *
     * <code>map&lt;string, string&gt; metadata = 3;</code>
     */

    public java.lang.String getMetadataOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetMetadata().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getKindBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, kind_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetMetadata(),
          MetadataDefaultEntryHolder.defaultEntry,
          3);
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getKindBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, kind_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetMetadata().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        metadata__ = MetadataDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(3, metadata__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof spec.proto.runtime.v1.LifecycleProto.ComponentConfig)) {
        return super.equals(obj);
      }
      spec.proto.runtime.v1.LifecycleProto.ComponentConfig other = (spec.proto.runtime.v1.LifecycleProto.ComponentConfig) obj;

      if (!getKind()
          .equals(other.getKind())) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!internalGetMetadata().equals(
          other.internalGetMetadata())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + KIND_FIELD_NUMBER;
      hash = (53 * hash) + getKind().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      if (!internalGetMetadata().getMap().isEmpty()) {
        hash = (37 * hash) + METADATA_FIELD_NUMBER;
        hash = (53 * hash) + internalGetMetadata().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static spec.proto.runtime.v1.LifecycleProto.ComponentConfig parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static spec.proto.runtime.v1.LifecycleProto.ComponentConfig parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static spec.proto.runtime.v1.LifecycleProto.ComponentConfig parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static spec.proto.runtime.v1.LifecycleProto.ComponentConfig parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static spec.proto.runtime.v1.LifecycleProto.ComponentConfig parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static spec.proto.runtime.v1.LifecycleProto.ComponentConfig parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static spec.proto.runtime.v1.LifecycleProto.ComponentConfig parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static spec.proto.runtime.v1.LifecycleProto.ComponentConfig parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static spec.proto.runtime.v1.LifecycleProto.ComponentConfig parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static spec.proto.runtime.v1.LifecycleProto.ComponentConfig parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static spec.proto.runtime.v1.LifecycleProto.ComponentConfig parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static spec.proto.runtime.v1.LifecycleProto.ComponentConfig parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(spec.proto.runtime.v1.LifecycleProto.ComponentConfig prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * The dynamic configuration of a component
     * </pre>
     *
     * Protobuf type {@code spec.proto.runtime.v1.ComponentConfig}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:spec.proto.runtime.v1.ComponentConfig)
        spec.proto.runtime.v1.LifecycleProto.ComponentConfigOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return spec.proto.runtime.v1.LifecycleProto.internal_static_spec_proto_runtime_v1_ComponentConfig_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 3:
            return internalGetMetadata();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 3:
            return internalGetMutableMetadata();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return spec.proto.runtime.v1.LifecycleProto.internal_static_spec_proto_runtime_v1_ComponentConfig_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                spec.proto.runtime.v1.LifecycleProto.ComponentConfig.class, spec.proto.runtime.v1.LifecycleProto.ComponentConfig.Builder.class);
      }

      // Construct using spec.proto.runtime.v1.LifecycleProto.ComponentConfig.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        kind_ = "";

        name_ = "";

        internalGetMutableMetadata().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return spec.proto.runtime.v1.LifecycleProto.internal_static_spec_proto_runtime_v1_ComponentConfig_descriptor;
      }

      @java.lang.Override
      public spec.proto.runtime.v1.LifecycleProto.ComponentConfig getDefaultInstanceForType() {
        return spec.proto.runtime.v1.LifecycleProto.ComponentConfig.getDefaultInstance();
      }

      @java.lang.Override
      public spec.proto.runtime.v1.LifecycleProto.ComponentConfig build() {
        spec.proto.runtime.v1.LifecycleProto.ComponentConfig result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public spec.proto.runtime.v1.LifecycleProto.ComponentConfig buildPartial() {
        spec.proto.runtime.v1.LifecycleProto.ComponentConfig result = new spec.proto.runtime.v1.LifecycleProto.ComponentConfig(this);
        int from_bitField0_ = bitField0_;
        result.kind_ = kind_;
        result.name_ = name_;
        result.metadata_ = internalGetMetadata();
        result.metadata_.makeImmutable();
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof spec.proto.runtime.v1.LifecycleProto.ComponentConfig) {
          return mergeFrom((spec.proto.runtime.v1.LifecycleProto.ComponentConfig)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(spec.proto.runtime.v1.LifecycleProto.ComponentConfig other) {
        if (other == spec.proto.runtime.v1.LifecycleProto.ComponentConfig.getDefaultInstance()) return this;
        if (!other.getKind().isEmpty()) {
          kind_ = other.kind_;
          onChanged();
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        internalGetMutableMetadata().mergeFrom(
            other.internalGetMetadata());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        spec.proto.runtime.v1.LifecycleProto.ComponentConfig parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (spec.proto.runtime.v1.LifecycleProto.ComponentConfig) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object kind_ = "";
      /**
       * <pre>
       * Required. Which kind of API you are using, e.g. `lock`, `state`
       * </pre>
       *
       * <code>string kind = 1;</code>
       * @return The kind.
       */
      public java.lang.String getKind() {
        java.lang.Object ref = kind_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          kind_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Required. Which kind of API you are using, e.g. `lock`, `state`
       * </pre>
       *
       * <code>string kind = 1;</code>
       * @return The bytes for kind.
       */
      public com.google.protobuf.ByteString
          getKindBytes() {
        java.lang.Object ref = kind_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          kind_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Required. Which kind of API you are using, e.g. `lock`, `state`
       * </pre>
       *
       * <code>string kind = 1;</code>
       * @param value The kind to set.
       * @return This builder for chaining.
       */
      public Builder setKind(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        kind_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Required. Which kind of API you are using, e.g. `lock`, `state`
       * </pre>
       *
       * <code>string kind = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearKind() {
        
        kind_ = getDefaultInstance().getKind();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Required. Which kind of API you are using, e.g. `lock`, `state`
       * </pre>
       *
       * <code>string kind = 1;</code>
       * @param value The bytes for kind to set.
       * @return This builder for chaining.
       */
      public Builder setKindBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        kind_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <pre>
       * Required. The component name, e.g. `state_demo`
       * </pre>
       *
       * <code>string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Required. The component name, e.g. `state_demo`
       * </pre>
       *
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Required. The component name, e.g. `state_demo`
       * </pre>
       *
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Required. The component name, e.g. `state_demo`
       * </pre>
       *
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Required. The component name, e.g. `state_demo`
       * </pre>
       *
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> metadata_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMetadata() {
        if (metadata_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              MetadataDefaultEntryHolder.defaultEntry);
        }
        return metadata_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableMetadata() {
        onChanged();;
        if (metadata_ == null) {
          metadata_ = com.google.protobuf.MapField.newMapField(
              MetadataDefaultEntryHolder.defaultEntry);
        }
        if (!metadata_.isMutable()) {
          metadata_ = metadata_.copy();
        }
        return metadata_;
      }

      public int getMetadataCount() {
        return internalGetMetadata().getMap().size();
      }
      /**
       * <pre>
       * Required. The dynamic configuration of this component
       * </pre>
       *
       * <code>map&lt;string, string&gt; metadata = 3;</code>
       */

      public boolean containsMetadata(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetMetadata().getMap().containsKey(key);
      }
      /**
       * Use {@link #getMetadataMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getMetadata() {
        return getMetadataMap();
      }
      /**
       * <pre>
       * Required. The dynamic configuration of this component
       * </pre>
       *
       * <code>map&lt;string, string&gt; metadata = 3;</code>
       */

      public java.util.Map<java.lang.String, java.lang.String> getMetadataMap() {
        return internalGetMetadata().getMap();
      }
      /**
       * <pre>
       * Required. The dynamic configuration of this component
       * </pre>
       *
       * <code>map&lt;string, string&gt; metadata = 3;</code>
       */

      public java.lang.String getMetadataOrDefault(
          java.lang.String key,
          java.lang.String defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetMetadata().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <pre>
       * Required. The dynamic configuration of this component
       * </pre>
       *
       * <code>map&lt;string, string&gt; metadata = 3;</code>
       */

      public java.lang.String getMetadataOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetMetadata().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearMetadata() {
        internalGetMutableMetadata().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <pre>
       * Required. The dynamic configuration of this component
       * </pre>
       *
       * <code>map&lt;string, string&gt; metadata = 3;</code>
       */

      public Builder removeMetadata(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableMetadata().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableMetadata() {
        return internalGetMutableMetadata().getMutableMap();
      }
      /**
       * <pre>
       * Required. The dynamic configuration of this component
       * </pre>
       *
       * <code>map&lt;string, string&gt; metadata = 3;</code>
       */
      public Builder putMetadata(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableMetadata().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <pre>
       * Required. The dynamic configuration of this component
       * </pre>
       *
       * <code>map&lt;string, string&gt; metadata = 3;</code>
       */

      public Builder putAllMetadata(
          java.util.Map<java.lang.String, java.lang.String> values) {
        internalGetMutableMetadata().getMutableMap()
            .putAll(values);
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:spec.proto.runtime.v1.ComponentConfig)
    }

    // @@protoc_insertion_point(class_scope:spec.proto.runtime.v1.ComponentConfig)
    private static final spec.proto.runtime.v1.LifecycleProto.ComponentConfig DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new spec.proto.runtime.v1.LifecycleProto.ComponentConfig();
    }

    public static spec.proto.runtime.v1.LifecycleProto.ComponentConfig getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ComponentConfig>
        PARSER = new com.google.protobuf.AbstractParser<ComponentConfig>() {
      @java.lang.Override
      public ComponentConfig parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ComponentConfig(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ComponentConfig> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ComponentConfig> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public spec.proto.runtime.v1.LifecycleProto.ComponentConfig getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spec_proto_runtime_v1_DynamicConfiguration_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_spec_proto_runtime_v1_DynamicConfiguration_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spec_proto_runtime_v1_ApplyConfigurationResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_spec_proto_runtime_v1_ApplyConfigurationResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spec_proto_runtime_v1_ComponentConfig_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_spec_proto_runtime_v1_ComponentConfig_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spec_proto_runtime_v1_ComponentConfig_MetadataEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_spec_proto_runtime_v1_ComponentConfig_MetadataEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n proto/runtime/v1/lifecycle.proto\022\025spec" +
      ".proto.runtime.v1\"X\n\024DynamicConfiguratio" +
      "n\022@\n\020component_config\030\001 \001(\0132&.spec.proto" +
      ".runtime.v1.ComponentConfig\"\034\n\032ApplyConf" +
      "igurationResponse\"\246\001\n\017ComponentConfig\022\014\n" +
      "\004kind\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022F\n\010metadata\030\003 " +
      "\003(\01324.spec.proto.runtime.v1.ComponentCon" +
      "fig.MetadataEntry\032/\n\rMetadataEntry\022\013\n\003ke" +
      "y\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\0012\203\001\n\tLifecycle" +
      "\022v\n\022ApplyConfiguration\022+.spec.proto.runt" +
      "ime.v1.DynamicConfiguration\0321.spec.proto" +
      ".runtime.v1.ApplyConfigurationResponse\"\000" +
      "BV\n\025spec.proto.runtime.v1B\016LifecycleProt" +
      "oZ-mosn.io/layotto/spec/proto/runtime/v1" +
      ";runtimeb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_spec_proto_runtime_v1_DynamicConfiguration_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_spec_proto_runtime_v1_DynamicConfiguration_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_spec_proto_runtime_v1_DynamicConfiguration_descriptor,
        new java.lang.String[] { "ComponentConfig", });
    internal_static_spec_proto_runtime_v1_ApplyConfigurationResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_spec_proto_runtime_v1_ApplyConfigurationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_spec_proto_runtime_v1_ApplyConfigurationResponse_descriptor,
        new java.lang.String[] { });
    internal_static_spec_proto_runtime_v1_ComponentConfig_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_spec_proto_runtime_v1_ComponentConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_spec_proto_runtime_v1_ComponentConfig_descriptor,
        new java.lang.String[] { "Kind", "Name", "Metadata", });
    internal_static_spec_proto_runtime_v1_ComponentConfig_MetadataEntry_descriptor =
      internal_static_spec_proto_runtime_v1_ComponentConfig_descriptor.getNestedTypes().get(0);
    internal_static_spec_proto_runtime_v1_ComponentConfig_MetadataEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_spec_proto_runtime_v1_ComponentConfig_MetadataEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
