name: Layotto CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # enable manually running the workflow
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven
      - name: Test with Maven
        run: mvn test
      - name: Codecov
        uses: codecov/codecov-action@v1