name: Publish preview_server docker image

on:
  push:
    branches: [main]
    paths:
       - 'examples-preview-service/**'
 
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Build preview_server Image
        run: |
          cp examples-preview-service/target/*.jar docker/preview_server
          docker build -t layotto/preview_server:latest -f docker/preview_server/Dockerfile .

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Image to DockerHub
        run: |
          docker push layotto/preview_server:latest


